//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG.SoftwareEstimationService.SqliteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumerationItem
    {
        public long EnumerationItemId { get; set; }
        public long EnumerationId { get; set; }
        public long EnumerationEnumerationId { get; set; }
        public string Name { get; set; }
    
        public virtual Enumeration Enumeration { get; set; }
    }
}
