//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG.SoftwareEstimationService.SqliteData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities1 : DbContext
    {
        public DatabaseEntities1()
            : base("name=DatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Enumeration> Enumerations { get; set; }
        public virtual DbSet<EnumerationItem> EnumerationItems { get; set; }
        public virtual DbSet<PartType> PartTypes { get; set; }
        public virtual DbSet<PartTypeProperty> PartTypeProperties { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<StoryPart> StoryParts { get; set; }
        public virtual DbSet<StoryPartProperty> StoryPartProperties { get; set; }
        public virtual DbSet<SystemInDevelopment> SystemInDevelopments { get; set; }
    }
}
