//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG.SoftwareEstimationService.SqliteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoryPart()
        {
            this.StoryPartProperties = new HashSet<StoryPartProperty>();
        }
    
        public long StoryPartId { get; set; }
        public Nullable<long> StoryId { get; set; }
        public Nullable<long> PartTypeId { get; set; }
        public string PartDescription { get; set; }
    
        public virtual PartType PartType { get; set; }
        public virtual Story Story { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryPartProperty> StoryPartProperties { get; set; }
    }
}
