//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG.SoftwareEstimationService.SqliteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Story()
        {
            this.StoryParts = new HashSet<StoryPart>();
        }
    
        public long StoryId { get; set; }
        public string TicketName { get; set; }
        public string StoryTitle { get; set; }
        public long SystemId { get; set; }
        public Nullable<double> ActualCompletetionDuration { get; set; }
        public Nullable<double> EstimatedCompletionDuration { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual SystemInDevelopment SystemInDevelopment { get; set; }
        public virtual SystemInDevelopment SystemInDevelopment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryPart> StoryParts { get; set; }
    }
}
